### PR TITLE
Bug fix in remove panel.

### PR DESCRIPTION
**Pull request by roastedmonk**

### CODE REVIEW

**Comment by noerw** [comment]
Thanks you, good catch!

**Comment by roastedmonk** [comment]
Will it be available in npm install?? 




Regards,


Subramaniam







On Wed, Feb 20, 2019 at 1:27 AM +0530, "Norwin" <notifications@github.com> wrote:












Merged #32 into master.

**Comment by noerw** [comment]
Yes, I just released v3.0.7

**Comment by roastedmonk** [comment]
Even min.js is updated rite?




Because that I didn't changed




Regards,


Subramaniam







On Wed, Feb 20, 2019 at 1:54 AM +0530, "Norwin" <notifications@github.com> wrote:












Yes, I just released v3.0.7

**Comment by noerw** [comment]
Sure ;)

**Comment by roastedmonk** [comment]
Thank you. 




Regards,


Subramaniam







On Wed, Feb 20, 2019 at 1:57 AM +0530, "Norwin" <notifications@github.com> wrote:












Sure ;)

**Pull request merged**
